MWIFIEX_VERSION = 5ad19e194f49ed9447bee7864eb562618ccaf9b1
MWIFIEX_SITE = $(call github,nxp-imx,mwifiex,$(MWIFIEX_VERSION))
MWIFIEX_LICENSE = GPL-2.0
MWIFIEX_LICENSE_FILES = LICENSE

MWIFIEX_MODULE_MAKE_OPTS = \
	KVER=$(LINUX_VERSION_PROBED) \
	KBASE=$(LINUX_DIR) \
	CROSS_COMPILE=$(TARGET_CROSS)

$(eval $(kernel-module))
$(eval $(generic-package))
